export const LINE_WIDTH = 1;
export const TYPE_SHIFT = 'shift';
export const TYPE_SHIFT_LEFT = 'left';
export const TYPE_SHIFT_RIGHT = 'right';
export const LINE_CAP = 'round';
export const LINE_JOIN = 'round';
export const FONT = '16px serif';
export const TEXT_BASELINE = 'middle';
export const MIN_WIDTH_SLIDER = 68;
